languag: node_js
node_js:
- lts/*
jobs:
  include:
  - stage: test
    script: npm run test
deploy:
  provider: heroku
  api_key:
    secure: d71pep2TA5nKA7uTOT09wCke8JGsH6QRQnnmgUnvaYS0SOL+RdoqUqvVqmCXGI3C4FHQNApiTVByKL5HnTAm6mZHrCAbOLa2T/9+GHo5YdoGIw9QckWMAbxRDu5/6BqRFGMttSpbG9j/WZowrKMT1AIQAmRZRfdAy+T2MZyhNBYhJwCIrwnWVM/Qs4ruSyGeJ1gHDcFYCwul7RaN4HaZFq1C/9BH3xKLCQgUxm3R8uhI4UM20TtdXBRRQ7MzOXOMOiBsmJxsxcJw6iXNs5RTHdAIZJkEzeC0dbRwhTDrlaU1iPu+zRkalvNfu5aeulowuCYMMhoG+BOdiX9T6WGwkV8SvT0YttM+sLd7wNRzsomofbVOv5c/k5ZRDOdKY/79Y8JJ6UnYA23EJwaw1we4aKmMv3+jkOyfBdqQEYD69GRdnrZzgCSILmyevszu+mzFHWTi5YlNHgr8ls2swt2+0Qz2Uu8fL4I3jD5hi0gj5jhNLH4loMmH3iIbLQ9d/paGVyRBgFi2/tKG7SJF2rB5LVjWfOhw2Ts9gLyWc16ndxpqhRIwVFN42yEn0dK21+drPGj6xX7M9K7EBiowUf8gPlioiQfWKhHS4fQwAGxVvCZo6IGgDfSKLvD87kMGpDj9UpxVbdXB3+m4Yxt41VMDzyTOShl8JG7FXxa29GQCUJo=
