language: node_js
node_js:
  - lts/*
jobs:
  include:
    - stage: test
      script: npm run test
deploy:
  provider: heroku
  api_key:
    secure: d816018e-df99-4c14-b322-abc0d595c71c
    app: travisaria
    on: staging
    run: 
      - restart
