languag: node_js
node_js:
- lts/*
jobs:
  include:
  - stage: test
    script: npm run test
deploy:
  provider: heroku
  api_key:
    secure: l4NOHfG5cKz6SlwucvgH7RcTb7ZDuqW2ymiqJWq0L5/fgLDVUWyfx6j7qquQ6gfeN6pz+/1Pdi0TiNl3lKRFZ7VWggyBaaK3a9irtDxXFnq7U9CZcU/83IU+zimHZmVinZH/5dtz0Lc8YSk7iRB7XfgOPUJ2crcE+KBFZ4NkPpOgTQogmdlwoS1VLG5zo5z+fnAtxzFyLVsUTa0Sq/EBYFU1fgBDJxHAbTTKCFknW6O29rzait6uidG2ajlmiZD4vdh3usRvFGLGk3W5aztawpnsDHaoOqBE2Su9nJG79GZKoLF/JYGhKXJLc9upkMkOcEcl5XmBXNzQuYbSTOj2ObhVYZmeFH+/KJ5yw+/VikISWto2ZkHjKoZzN+5llr6C6Bfkb5XRVy8OlQcLl7ufgG9Oosv10GJtfYlIWVNLLhlCZhjxn78FiFsWj87Mg7tLcRTcyMgE8SDvtmuz6KFvqUWd4oNfdfpa/ifCkDcWcQOnssO7+2qDfuQp6TFBMD6CJZ7aKiWC6aUyucf9axV+urZO3hbn5obwi/E4ofU8r4iEZx4FPK+3N2PjMbg9/OJSNKHzQ3MBYA0imksohf5pcUq8d1d+16gIhJPxRUWz9xE7UaDD26veIXTX+e1dUXUJDQ49yTTVg+4vMlxQmC9u6JAoMlN5YOX4yFhxdCf5Deg=
